# -*- coding: utf-8 -*-
"""BDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIntTqr-t1ryy8x46nWFtrYe7zaWrX05
"""

!pip install streamlit pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# # paste your FULL streamlit code here
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# from sklearn.ensemble import RandomForestRegressor
# from openai import OpenAI
# import os
# 
# st.markdown("""
# <style>
# body {
#     background: linear-gradient(to right, #141e30, #243b55);
#     color: white;
# }
# 
# .stMetric {
#     background: rgba(255,255,255,0.1);
#     padding: 15px;
#     border-radius: 15px;
#     backdrop-filter: blur(10px);
# }
# 
# .stButton>button {
#     border-radius: 10px;
#     background: linear-gradient(45deg, #ff416c, #ff4b2b);
#     color: white;
#     font-weight: bold;
# }
# 
# .css-1d391kg {
#     background: rgba(255,255,255,0.05);
# }
# </style>
# """, unsafe_allow_html=True)
# # ---------------- PAGE ----------------
# st.set_page_config(page_title="AI Dynamic Pricing Dashboard", layout="wide")
# 
# st.title(" AI Dynamic Pricing Simulator")
# st.markdown("Smart pricing system with AI + advanced analytics")
# 
# # ---------------- API KEY ----------------
# client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
# 
# # ---------------- SIDEBAR ----------------
# st.sidebar.title(" Control Panel")
# 
# demand = st.sidebar.slider("Demand", 1, 100, 60)
# traffic = st.sidebar.selectbox("Traffic", ["Low", "Medium", "High"])
# weather = st.sidebar.selectbox("Weather", ["Clear", "Rain", "Storm"])
# time_val = st.sidebar.selectbox("Time", ["Off-Peak", "Normal", "Peak"])
# 
# traffic_map = {"Low":1, "Medium":2, "High":3}
# weather_map = {"Clear":1, "Rain":2, "Storm":3}
# time_map = {"Off-Peak":1, "Normal":2, "Peak":3}
# 
# # ---------------- DATA ----------------
# np.random.seed(42)
# df = pd.DataFrame({
#     "demand": np.random.randint(1,100,500),
#     "traffic": np.random.randint(1,4,500),
#     "weather": np.random.randint(1,4,500),
#     "time": np.random.randint(1,4,500),
# })
# 
# df["price"] = (
#     df["demand"] * 2 +
#     df["traffic"] * 20 +
#     df["weather"] * 15 +
#     df["time"] * 25
# )
# 
# # ---------------- MODEL ----------------
# X = df[["demand","traffic","weather","time"]]
# y = df["price"]
# 
# model = RandomForestRegressor()
# model.fit(X,y)
# 
# # ---------------- PREDICTION ----------------
# input_data = np.array([[demand,
#                         traffic_map[traffic],
#                         weather_map[weather],
#                         time_map[time_val]]])
# 
# price = model.predict(input_data)[0]
# 
# surge_multiplier = round(price / 100, 2)
# 
# if surge_multiplier > 2:
#     st.error(f"🚨 EXTREME SURGE x{surge_multiplier}")
# elif surge_multiplier > 1.5:
#     st.warning(f"⚡ Surge x{surge_multiplier}")
# else:
#     st.success(f"✅ Normal x{surge_multiplier}")
# # ---------------- ALERT ----------------
# if price > 200:
#     st.error("🚨 Surge Pricing Active!")
# elif price > 150:
#     st.warning("⚡ Moderate Surge")
# else:
#     st.success("✅ Normal Pricing")
# 
# # ---------------- KPI ----------------
# c1, c2, c3, c4 = st.columns(4)
# c1.metric(" Price", f"₹{price:.2f}")
# c2.metric(" Demand", demand)
# c3.metric(" Traffic", traffic)
# c4.metric(" Weather", weather)
# 
# # ================= VISUALIZATIONS =================
# 
# # 1
# st.subheader("1. Demand vs Price Trend")
# fig = px.line(df.sort_values("demand"), x="demand", y="price")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Demand, Y = Price → Price increases as demand increases")
# 
# # 2
# st.subheader("2. Traffic Impact on Pricing")
# fig = px.bar(df, x="traffic", y="price", color="traffic")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Traffic, Y = Price → Higher traffic leads to higher price")
# 
# # 3
# st.subheader("3. Weather Impact Distribution")
# fig = px.box(df, x="weather", y="price", color="weather")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Weather, Y = Price → Bad weather increases price variability")
# 
# # 4
# st.subheader("4. Time-based Price Distribution")
# fig = px.violin(df, x="time", y="price", box=True)
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Time, Y = Price → Peak hours show higher prices")
# 
# # 5
# st.subheader("5. Traffic vs Time Heatmap")
# pivot = df.pivot_table(values="price", index="traffic", columns="time")
# fig = px.imshow(pivot, text_auto=True)
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Time, Y = Traffic → Color intensity shows price")
# 
# # 6
# st.subheader("6. 3D Pricing Relationship")
# fig = px.scatter_3d(df, x="demand", y="traffic", z="price", color="price")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Demand, Y = Traffic, Z = Price")
# 
# # 7
# st.subheader("7. Feature Importance")
# importance = model.feature_importances_
# features = ["demand","traffic","weather","time"]
# imp_df = pd.DataFrame({"feature":features,"importance":importance})
# fig = px.bar(imp_df, x="feature", y="importance", color="importance")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Feature, Y = Importance → Shows most influential factor")
# 
# # 8
# st.subheader("8. Price Distribution")
# fig = px.histogram(df, x="price", nbins=40)
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Price, Y = Frequency")
# 
# # 9
# st.subheader("9. Scatter Matrix")
# fig = px.scatter_matrix(df, dimensions=["demand","traffic","weather","time","price"])
# st.plotly_chart(fig, use_container_width=True)
# st.caption("Shows relationships between all variables")
# 
# # 10
# st.subheader("10. Bubble Chart")
# fig = px.scatter(df, x="demand", y="price",
#                  size="weather", color="traffic")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("X = Demand, Y = Price, Size = Weather, Color = Traffic")
# 
# # 11
# st.subheader("11. Animated Pricing Simulation")
# df["frame"] = np.random.randint(1,10,len(df))
# fig = px.scatter(df, x="demand", y="price",
#                  animation_frame="frame",
#                  color="traffic")
# st.plotly_chart(fig, use_container_width=True)
# st.caption("Shows price changes over scenarios")
# 
# # 12
# st.subheader("12. Correlation Heatmap")
# corr = df.corr()
# fig = px.imshow(corr, text_auto=True)
# st.plotly_chart(fig, use_container_width=True)
# st.caption("Shows correlation between variables")
# 
# # ---------------- LLM ----------------
# prompt = f"""
# You are an Uber pricing AI.
# 
# Explain dynamically:
# - Why price surged
# - What factors influenced it most
# - Give recommendation (wait or book now)
# 
# Inputs:
# Demand: {demand}
# Traffic: {traffic}
# Weather: {weather}
# Time: {time_val}
# Price: {price}
# 
# Make it smart, human-like and slightly dramatic.
# """
# 
# # ---------------- MAP VISUAL ----------------
# st.subheader("🗺️ Live Ride Demand Map")
# 
# # Simulated locations (Bangalore-like area)
# map_df = pd.DataFrame({
#     "lat": np.random.uniform(12.90, 13.10, 200),
#     "lon": np.random.uniform(77.50, 77.70, 200),
#     "demand": np.random.randint(1,100,200)
# })
# 
# st.map(map_df)
# 
# st.caption("Map shows ride demand density across locations (higher demand → higher surge pricing)")

from pyngrok import ngrok
import subprocess
import time

# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
# You can get one from your ngrok dashboard: https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("3BwpEVJbhdWZRuaWGtiIwHhhJXB_7ABXcJkgz6rCREMwq6iYp")

# Start streamlit
process = subprocess.Popen(["streamlit", "run", "app.py"])

# Wait for app to start
time.sleep(5)

# Create public URL
public_url = ngrok.connect(8501)
print("Your app is live at:", public_url)

