# -*- coding: utf-8 -*-
"""BDA_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10kY5fU00k4-Wvd3bzeIN3CxCI-z6A6Vs
"""

!pip install streamlit pyngrok openai scikit-learn plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# from sklearn.ensemble import RandomForestRegressor
# from openai import OpenAI
# import os
# import time
# 
# st.set_page_config(page_title="AI Dynamic Pricing Dashboard", layout="wide")
# 
# st.title("AI Dynamic Pricing Simulator")
# 
# # API KEY
# client = OpenAI(api_key="")
# 
# # SIDEBAR
# demand = st.sidebar.slider("Demand", 1, 100, 60)
# traffic = st.sidebar.selectbox("Traffic", ["Low", "Medium", "High"])
# weather = st.sidebar.selectbox("Weather", ["Clear", "Rain", "Storm"])
# time_val = st.sidebar.selectbox("Time", ["Off-Peak", "Normal", "Peak"])
# 
# traffic_map = {"Low":1, "Medium":2, "High":3}
# weather_map = {"Clear":1, "Rain":2, "Storm":3}
# time_map = {"Off-Peak":1, "Normal":2, "Peak":3}
# 
# # DATA
# np.random.seed(42)
# df = pd.DataFrame({
#     "demand": np.random.randint(1,100,500),
#     "traffic": np.random.randint(1,4,500),
#     "weather": np.random.randint(1,4,500),
#     "time": np.random.randint(1,4,500),
# })
# 
# df["price"] = df["demand"]*2 + df["traffic"]*20 + df["weather"]*15 + df["time"]*25
# 
# # BIG DATA
# st.subheader("Big Data Simulation")
# big_df = pd.DataFrame({
#     "demand": np.random.randint(1,100,100000),
#     "traffic": np.random.randint(1,4,100000),
#     "weather": np.random.randint(1,4,100000),
#     "time": np.random.randint(1,4,100000),
# })
# st.write("Dataset size:", len(big_df))
# 
# # STREAMING
# if st.button("Simulate Live Data"):
#     for i in range(3):
#         st.write({
#             "demand": np.random.randint(1,100),
#             "traffic": np.random.randint(1,4),
#             "weather": np.random.randint(1,4),
#             "time": np.random.randint(1,4)
#         })
#         time.sleep(1)
# 
# # MODEL
# X = df[["demand","traffic","weather","time"]]
# y = df["price"]
# 
# model = RandomForestRegressor()
# model.fit(X,y)
# 
# # PREDICT
# input_data = np.array([[demand,traffic_map[traffic],weather_map[weather],time_map[time_val]]])
# price = model.predict(input_data)[0]
# 
# st.metric("Predicted Price", f"₹{price:.2f}")
# 
# # VISUALS
# fig = px.line(df.sort_values("demand"), x="demand", y="price")
# st.plotly_chart(fig)
# st.caption("X = Demand, Y = Price")
# 
# fig = px.histogram(df, x="price")
# st.plotly_chart(fig)
# 
# fig = px.scatter_3d(df, x="demand", y="traffic", z="price")
# st.plotly_chart(fig)
# 
# # MAP
# map_df = pd.DataFrame({
#     "lat": np.random.uniform(12.90, 13.10, 200),
#     "lon": np.random.uniform(77.50, 77.70, 200),
# })
# st.map(map_df)
# 
# # LLM
# if st.button("Explain Price"):
#     prompt = f"Explain why price is {price} based on demand, traffic, weather and time"
#     res = client.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[{"role":"user","content":prompt}]
#     )
#     st.write(res.choices[0].message.content)
#

from pyngrok import ngrok
import subprocess
import time

# Replace 'YOUR_AUTHTOKEN' with your actual ngrok authtoken
# You can get one from your ngrok dashboard: https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.set_auth_token("")

# Start streamlit
process = subprocess.Popen(["streamlit", "run", "app.py"])

# Wait for app to start
time.sleep(5)

# Create public URL
public_url = ngrok.connect(8501)
print("Your app is live at:", public_url)

